### ISSUE TITLE
SDR dpn-dev connectivity

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/dpn-sync#27]
SDR connections to other DPN-dev nodes
- [x] HTTPS connections
  - [x] APTrust
    - [x] SDR -> APTrust
    - [x] APTrust -> SDR
  - [x] Chronopolis
    - [x] SDR -> Chron
    - [x] Chron -> SDR
  - [x] Hathi
    - [x] SDR -> Hathi
    - [x] Hathi -> SDR
  - [x] TDR
    - [x] SDR -> TDR
    - [x] TDR -> SDR
- [x] SSH/RSYNC connections
  - [x] APTrust
    - [x] SDR -> APTrust
      - works if we append `'dpn.'` to the username
      - might require changes to `dpn-sync` project
    - [x] APTrust -> SDR
  - [x] Chronopolis
    - [x] SDR -> Chron
    - [x] Chron -> SDR
  - [x] Hathi
    - X SDR -> Hathi
      - Hathi-dev is replication only, there is no plan to open up ssh/rsync to remote nodes
    - [x] Hathi -> SDR
  - [x] TDR
    - [x] SDR -> TDR
    - [x] TDR -> SDR

**Comment by dazza-codes** [comment]
An example ssh/rsync test

``` sh
ksu sdr
cd
ID_RSA_FILE=/path_to_id_rsa_file # see `history` for examples
REMOTE_NODE=example.com
ssh -i $ID_RSA_FILE "sdr@$REMOTE_NODE"
rsync -avPL -e "'ssh -i $ID_RSA_FILE'" "sdr@${REMOTE_NODE}:/home/sdr/staging/test.tar" ./
```

Tested outbound ssh connections and everything fails except TDR; notified node developers of the failures (Oct 14, 2016).

**Comment by dazza-codes** [comment]
We can ssh into Hathi-dev, but it currently requires a `dpn.` prefix on the user account.  The dpn-sync project currently uses a common user account to access all the remote nodes.  To change this for one remote node would require changes to configs/code/docs in dpn-sync.

**Comment by Pcolar** [comment]
Let's discuss at today's meeting. I don't want to introduce changes to the configs/code/docs in dpn-sync this late in the release process.

**Comment by dazza-codes** [comment]
Updated node details for 'hathi' and 'aptrust' nodes on dpn-server for SDR-dev.

**Comment by dazza-codes** [comment]
@malakai97 says Hathi-dev is 'replicating only so there's no plan of opening up ssh/rsync for now'.

**Comment by dazza-codes** [comment]
Mike Ritter confirmed that Chron-dev node can access SDR-dev node via HTTPS and SSH.

**Comment by dazza-codes** [comment]
We resolved the HTTPS connection to Hathi-dev node.

**Comment by dazza-codes** [comment]
The SDR-dev node is now fully connected to DPN-dev nodes.  The only exception, by design, is that SDR-dev cannot ssh/rsync to Hathi-dev (because the latter is designed to be a replication-only node).
